### ISSUE TITLE
Unable to Enable plugin inside MusicBee

### ISSUE THREAD

**Issue by Senchi3** [maybeclean/musicbee-rich-presence#1]
I've tried everything I can, from running the program with admin privileges, to getting Visual Studio and building the DLL myself, to just flat out reinstalling MusicBee and I just have no idea what's going on. Will post the error log below:

`30/04/2021 22:41:25 - 10.0.19042.0 - 3.4.7764.37422D - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at MusicBeePlugin.Plugin.Initialise(IntPtr apiInterfacePtr)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at #=z_aDAVc7sMkwkYxQETg==..ctor(#=zoKrwgApZgrrQua03HQ== #=zmYRlZmg=)`

And here is the error message:
![image](https://user-images.githubusercontent.com/28656059/116770273-08db9280-aa08-11eb-877b-49e54276569b.png)

**Comment by maybeclean** [comment]
Looks like your auth token isn't being set for some reason, are you logged into discord app and do you have .ldb files in `%appdata%\discord\Local Storage\leveldb` ?

**Comment by Senchi3** [comment]
I do have .ldb files in `%appdata%\discord\Local Storage\leveldb`, and I _am_ logged into Discord.

**Comment by maybeclean** [comment]
Forgot about this for a couple days, plugin should now be working without any issues. Feel free to try it out

**Comment by KBxR** [comment]
Hi, I'm still getting errors, im using the precompiled binaries 
`14-May-21 7:08:28 PM - 10.0.19043.0 - 3.4.7764.37422D - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at MusicBeePlugin.Plugin.Initialise(IntPtr apiInterfacePtr)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at #=z_aDAVc7sMkwkYxQETg==..ctor(#=zoKrwgApZgrrQua03HQ== #=zmYRlZmg=)`
